# GitHub Pages Configuration for Student Reflection Portal

title: "Student Reflection Portal"
description: "Interactive student reflection page with internationalization support"
baseurl: "/Course-Management-Platform-Backend-Service"
url: "https://Latjor-Wuon.github.io"
markdown: kramdown
highlighter: rouge
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock

# Include files
include:
  - _pages
